name: 'Wait'
description: 'Wait a designated number of milliseconds'
inputs:
  host:
    description: 'Your Jira hostname'
    required: true
  username:
    description: 'The email of the user'
    required: true
  token:
    description: 'The token of the user'
    required: true
  projectId:
    description: 'The ID of the project in which to create the version'
    required: true
  version:
    description: 'The version to manage in Jira'
    required: true
  issueIds:
    description: 'A JSON array of Jira issue IDs to be associated with the version'
    required: true
    default: '[]'
  release:
    description: 'Whether to release the version or not'
    required: true
    default: false
  releaseNotes:
    description: 'The release notes to add to the release in Markdown format'
    required: true
    default: ''
outputs:
  versionUrl: # output will be available to future steps
    description: 'The URL to the version in Jira'
runs:
  using: 'node12'
  main: 'dist/index.js'
